[package]
name = "cargo-arch"
version = "0.1.0"
authors = ["Chiu-Hsiang Hsu <wdv4758h@gmail.com>"]
license = "Apache-2.0"
readme = "README.rst"
description = "Rust Arch Linux package packer"
repository = "https://github.com/wdv4758h/cargo-arch/"
keywords = ["cargo", "package"]

[dependencies]
clap = { version = "2.10.0", features = ["yaml"] }
rustc-serialize = "0.3.19"
toml = "0.2.0"

[package.metadata.arch]
arch = ["x86_64"]

[profile.release]
lto = true
